# Generated by Django 3.1.5 on 2021-03-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
    ]
