# Generated by Django 3.1.5 on 2021-02-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
